// External data file: defines EPIC_QUESTS to keep large data out of script.js
// This file should be included before script.js in index.html

window.EPIC_QUESTS_BASE =
[
  {
    "name": "A Small Problem",
    "requirements": [],
    "lvl": 20,
    "patron": "House Phiarlan",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 20075,
    "tokens": 1
  },
  {
    "name": "Partycrashers",
    "requirements": [],
    "lvl": 20,
    "patron": "House Phiarlan",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 16318,
    "tokens": 1
  },
  {
    "name": "The Snitch",
    "requirements": [],
    "lvl": 20,
    "patron": "House Phiarlan",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 14303,
    "tokens": 0.7
  },
  {
    "name": "Under the Big Top",
    "requirements": [
      "A Small Problem",
      "Partycrashers",
      "The Snitch"
    ],
    "lvl": 20,
    "patron": "House Phiarlan",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 16188,
    "tokens": 1
  },
  {
    "name": "Storm the Beaches",
    "requirements": [],
    "lvl": 20,
    "patron": "House Deneith",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 11625,
    "tokens": 0.6
  },
  {
    "name": "The Black Loch",
    "requirements": [],
    "lvl": 20,
    "patron": "House Deneith",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 12259,
    "tokens": 1
  },
  {
    "name": "Bargain of Blood",
    "requirements": [],
    "lvl": 20,
    "patron": "House Deneith",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 9551,
    "tokens": 0.6
  },
  {
    "name": "The Tide Turns",
    "requirements": [
      "Storm the Beaches",
      "The Black Loch",
      "Bargain of Blood"
    ],
    "lvl": 20,
    "patron": "House Deneith",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 14406,
    "tokens": 1
  },
  {
    "name": "Devil Assault",
    "requirements": [],
    "lvl": 21,
    "patron": "The Coin Lords",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 18142,
    "tokens": 1.5
  },
  {
    "name": "The Chronoscope",
    "requirements": [],
    "lvl": 21,
    "patron": "The Coin Lords",
    "favor": 15,
    "difficulty": null,
    "baseXP": 25456,
    "tokens": 1
  },
  {
    "name": "The Lords of Dust",
    "requirements": [],
    "lvl": 21,
    "patron": "The Silver Flame",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 18525,
    "tokens": 1
  },
  {
    "name": "Servants of the Overlord",
    "requirements": [
      "The Lords of Dust"
    ],
    "lvl": 21,
    "patron": "The Silver Flame",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 24605,
    "tokens": 1
  },
  {
    "name": "The Spinner of Shadows",
    "requirements": [
      "The Lords of Dust",
      "Servants of the Overlord"
    ],
    "lvl": 21,
    "patron": "The Silver Flame",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 22355,
    "tokens": 1
  },
  {
    "name": "Beyond the Rift",
    "requirements": [
      "The Lords of Dust",
      "Servants of the Overlord",
      "The Spinner of Shadows"
    ],
    "lvl": 21,
    "patron": "The Silver Flame",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 24969,
  },
  {
    "name": "Violent Delights",
    "requirements": [],
    "lvl": 21,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 7580,
  },
  {
    "name": "The Hobgoblin Horde",
    "requirements": [],
    "lvl": 21,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 10317,
  },
  {
    "name": "Watch Your Step",
    "requirements": [],
    "lvl": 21,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 7125,
  },
  {
    "name": "Obstructing the Orcs",
    "requirements": [],
    "lvl": 21,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 7580,
  },
  {
    "name": "The Bugbear Bandits",
    "requirements": [],
    "lvl": 21,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 7125,
  },
  {
    "name": "Treasure Hunt",
    "requirements": [],
    "lvl": 21,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 8036,
  },
  {
    "name": "Caged Beast",
    "requirements": [],
    "lvl": 21,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 8219,
  },
  {
    "name": "Total Chaos",
    "requirements": [],
    "lvl": 22,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 14392,
  },
  {
    "name": "An Offering of Blood",
    "requirements": [],
    "lvl": 21,
    "patron": "The Free Agents",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 23997,
    "tokens": 1
  },
  {
    "name": "The Chamber of Raiyum",
    "requirements": [],
    "lvl": 22,
    "patron": "The Free Agents",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 28500,
    "tokens": 1.5
  },
  {
    "name": "Chains of Flame",
    "requirements": [],
    "lvl": 22,
    "patron": "The Free Agents",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 30277,
    "tokens": 2.5
  },
      {
    "name": "Against the Demon Queen",
    "requirements": [
      "An Offering of Blood",
      "The Chamber of Raiyum",
      "Chains of Flame"
    ],
    "lvl": 22,
    "patron": "The Free Agents",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 28500,
    "tokens": 1.5
  },
  {
    "name": "Zawabi's Revenge",
    "requirements": [
      "An Offering of Blood",
      "The Chamber of Raiyum",
      "Chains of Flame",
      "Against the Demon Queen"
    ],
    "lvl": 22,
    "patron": "The Free Agents",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 22857,
    "tokens": 1
  },
  {
    "name": "Impossible Demands",
    "requirements": [],
    "lvl": 21,
    "patron": "Purple Dragon Knights",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 11472,
  },
  {
    "name": "The Unquiet Graves",
    "requirements": [],
    "lvl": 21,
    "patron": "Purple Dragon Knights",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 12201,
  },
  {
    "name": "The Lost Thread",
    "requirements": [],
    "lvl": 21,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 10342,
  },
  {
    "name": "The Battle for Eveningstar",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread"
    ],
    "lvl": 21,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 19680,
  },
  {
    "name": "Spies in the House",
    "requirements": [],
    "lvl": 21,
    "patron": "House Deneith",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 34941,
    "tokens": 1.5
  },
  {
    "name": "The Claw of Vulkoor",
    "requirements": [],
    "lvl": 21,
    "patron": "House Kundarak",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 15059,
    "tokens": 0.7
  },
  {
    "name": "Fathom the Depths",
    "requirements": [],
    "lvl": 21,
    "patron": "House Kundarak",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 21078,
    "tokens": 0.6
  },
  {
    "name": "The Last Stand",
    "requirements": [],
    "lvl": 21,
    "patron": "House Kundarak",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 11776,
    "tokens": 0.4
  },
  {
    "name": "Into the Deep",
    "requirements": [
      "The Claw of Vulkoor",
      "Fathom the Depths",
      "The Last Stand"
    ],
    "lvl": 21,
    "patron": "House Kundarak",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 27645,
    "tokens": 1
  },
  {
    "name": "Tharashk Arena",
    "requirements": [],
    "lvl": 21,
    "patron": "House Kundarak",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 10499,
    "tokens": 1
  },
  {
    "name": "The Prisoner",
    "requirements": [],
    "lvl": 21,
    "patron": "House Kundarak",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 16701,
    "tokens": 1
  },
  {
    "name": "Jungle of Khyber",
    "requirements": [],
    "lvl": 22,
    "patron": "House Kundarak",
    "favor": 27,
    "difficulty": "R",
    "baseXP": 24784,
    "tokens": 1.5
  },
  {
    "name": "Haywire Foundry",
    "requirements": [],
    "lvl": 22,
    "patron": "House Kundarak",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 25866,
    "tokens": 1.5
  },
  {
    "name": "The Vault of Night",
    "requirements": [
      "Tharashk Arena",
      "The Prisoner",
      "Jungle of Khyber",
      "Haywire Foundry"
    ],
    "lvl": 22,
    "patron": "House Kundarak",
    "favor": 27,
    "difficulty": null,
    "baseXP": 56715,
    "tokens": 1.5
  },
  {
    "name": "Plane of Night",
    "requirements": [
      "Tharashk Arena",
      "The Prisoner",
      "Jungle of Khyber",
      "Haywire Foundry",
      "Plane of Night"
    ],
    "lvl": 22,
    "patron": "House Kundarak",
    "favor": 15,
    "difficulty": null,
    "baseXP": 9689,
    "tokens": 1
  },
  {
    "name": "Another Man's Treasure",
    "requirements": [],
    "lvl": 21,
    "patron": "The Twelve",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 18889,
  },
  {
    "name": "Kind of a Big Deal",
    "requirements": [],
    "lvl": 21,
    "patron": "The Twelve",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 18342,
  },
  {
    "name": "Don't Drink the Water",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar"
    ],
    "lvl": 22,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 15282,
  },
  {
    "name": "In the Belly of the Beast",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar"
    ],
    "lvl": 22,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 25067,
  },
  {
    "name": "The House of Death Undone",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar"
    ],
    "lvl": 22,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 15417,
  },
  {
    "name": "The House of Rusted Blades",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar"
    ],
    "lvl": 22,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 12022,
  },
  {
    "name": "The House of Broken Chains",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar"
    ],
    "lvl": 22,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 16148,
  },
  {
    "name": "The Portal Opens",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar",
      "The House of Death Undone",
      "The House of Rusted Blades",
      "The House of Broken Chains"
    ],
    "lvl": 22,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 18906,
  },
  {
    "name": "Trial by Fury",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar",
      "The House of Death Undone",
      "The House of Rusted Blades",
      "The House of Broken Chains",
      "The Portal Opens"
    ],
    "lvl": 23,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 27280,
  },
  {
    "name": "The Deal and the Demon",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar",
      "The House of Death Undone",
      "The House of Rusted Blades",
      "The House of Broken Chains",
      "The Portal Opens"
    ],
    "lvl": 23,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 16434,
  },
  {
    "name": "Reclaiming the Rift",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar",
      "The House of Death Undone",
      "The House of Rusted Blades",
      "The House of Broken Chains",
      "The Portal Opens"
    ],
    "lvl": 23,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 16434,
  },
  {
    "name": "Epic End of Eberron Saga",
    "isSaga": true,
    "requirements": [
      "The Lords of Dust",
      "Servants of the Overlord",
      "The Spinner of Shadows",
      "Beyond the Rift",
      "The House of Death Undone",
      "The House of Rusted Blades",
      "The House of Broken Chains",
      "The Portal Opens",
      "Trial by Fury",
      "The Deal and the Demon",
      "Reclaiming the Rift"
    ],
    "xp": 102000
  },
  {
    "name": "Epic Underdark Saga",
    "isSaga": true,
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar",
      "The House of Death Undone",
      "The House of Rusted Blades",
      "The House of Broken Chains",
      "The Portal Opens",
      "Trial by Fury",
      "The Deal and the Demon",
      "Reclaiming the Rift",
      "Don't Drink the Water",
      "In the Belly of the Beast"
    ],
    "xp": 134000
  },
  {
    "name": "The Friar's Niece",
    "requirements": [],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 8495,
  },
  {
    "name": "Return to the Sanctuary",
    "requirements": [
      "The Friar's Niece"
    ],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 6,
    "difficulty": "R",
    "baseXP": 9464,
  },
  {
    "name": "The Old Archives",
    "requirements": [
      "The Friar's Niece",
      "Return to the Sanctuary"
    ],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 13340,
  },
  {
    "name": "The Crypt of Gerard Dryden",
    "requirements": [
      "The Friar's Niece",
      "Return to the Sanctuary",
      "The Old Archives"
    ],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 16434,
  },
  {
    "name": "Setting the Wards: The Lower Cathedral",
    "requirements": [
      "The Friar's Niece",
      "Return to the Sanctuary",
      "The Old Archives",
      "The Crypt of Gerard Dryden"
    ],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 18185,
  },
  {
    "name": "Setting the Wards: The Patriarch's Crypt",
    "requirements": [
      "The Friar's Niece",
      "Return to the Sanctuary",
      "The Old Archives",
      "The Crypt of Gerard Dryden",
      "Setting the Wards: The Lower Cathedral"
    ],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 18185,
  },
  {
    "name": "Endgame: Marguerite",
    "requirements": [
      "The Friar's Niece",
      "Return to the Sanctuary",
      "The Old Archives",
      "The Crypt of Gerard Dryden",
      "Setting the Wards: The Lower Cathedral",
      "Setting the Wards: The Patriarch's Crypt"
    ],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 14309,
  },
  {
    "name": "Endgame: The Archbishop's Fate",
    "requirements": [
      "The Friar's Niece",
      "Return to the Sanctuary",
      "The Old Archives",
      "The Crypt of Gerard Dryden",
      "Setting the Wards: The Lower Cathedral",
      "Setting the Wards: The Patriarch's Crypt",
      "Endgame: Marguerite"
    ],
    "lvl": 23,
    "patron": "The Silver Flame",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 5817,
  },
  {
    "name": "Outbreak",
    "requirements": [],
    "lvl": 23,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 13885,
  },
  {
    "name": "Overgrowth",
    "requirements": [],
    "lvl": 23,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 10621,
  },
  {
    "name": "Thorn and Paw",
    "requirements": [],
    "lvl": 23,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 21092,
  },
  {
    "name": "The Druid's Curse",
    "requirements": [
      "Outbreak",
      "Overgrowth",
      "Thorn and Paw"
    ],
    "lvl": 23,
    "patron": "The Harpers",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 22513,
  },
  {
    "name": "Memory Lapse",
    "requirements": [],
    "lvl": 23,
    "patron": "The Twelve",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 19471,
  },
  {
    "name": "Caught in the Web",
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar",
      "The House of Death Undone",
      "The House of Rusted Blades",
      "The House of Broken Chains",
      "The Portal Opens",
      "Trial by Fury",
      "The Deal and the Demon",
      "Reclaiming the Rift"
    ],
    "lvl": 24,
    "patron": "Purple Dragon Knights",
    "favor": 24,
    "difficulty": null,
    "baseXP": 19437,
  },
  {
    "name": "Feast or Famine",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 21565,
  },
  {
    "name": "Return to Cabal for One",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 13851,
  },
  {
    "name": "The Crucible",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 47895,
  },
  {
    "name": "Trial by Fire",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 18904,
  },
  {
    "name": "The Maze of Madness",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 16244,
  },
  {
    "name": "Return to Madstone Crater",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 24,
    "difficulty": "R",
    "baseXP": 30077,
  },
  {
    "name": "Return to Prison of the Planes",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 18240,
  },
  {
    "name": "Foundation of Discord",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 18373,
  },
  {
    "name": "A Cry for Help",
    "requirements": [],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 22894,
  },
  {
    "name": "Return to Gianthold Tor",
    "requirements": [
      "Return to Madstone Crater",
      "Return to Prison of the Planes",
      "Return to Cabal for One"
    ],
    "lvl": 24,
    "patron": "Agents of Argonnessen",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 27407,
  },
  {
    "name": "Epic Gianthold Saga",
    "isSaga": true,
    "requirements": [
      "Feast or Famine",
      "Return to Cabal for One",
      "The Crucible",
      "Trial by Fire",
      "The Maze of Madness",
      "Return to Madstone Crater",
      "Return to Prison of the Planes",
      "Foundation of Discord",
      "A Cry for Help",
      "Return to Gianthold Tor"
    ],
    "xp": 92000
  },
  {
    "name": "Detour",
    "requirements": [],
    "lvl": 24,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 21337,
  },
  {
    "name": "Rest Stop",
    "requirements": [],
    "lvl": 24,
    "patron": "The Harpers",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 15517,
  },
  {
    "name": "A Stay at the Inn",
    "requirements": [],
    "lvl": 24,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 12853,
  },
  {
    "name": "Lost in the Swamp",
    "requirements": [],
    "lvl": 24,
    "patron": "The Harpers",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 16444,
  },
  {
    "name": "The End of the Road",
    "requirements": [
      "Detour",
      "Rest Stop",
      "A Stay at the Inn",
      "Lost in the Swamp"
    ],
    "lvl": 24,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 21724,
  },
  {
    "name": "The Price of Freedom",
    "requirements": [],
    "lvl": 25,
    "patron": "The Twelve",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 27371,
  },
  {
    "name": "A Legend Revisited",
    "requirements": [],
    "lvl": 25,
    "patron": "The Free Agents",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 26550,
  },
  {
    "name": "Old Tomb, New Tenants",
    "requirements": [],
    "lvl": 25,
    "patron": "The Free Agents",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 21352,
  },
  {
    "name": "Prove Your Worth",
    "requirements": [],
    "lvl": 25,
    "patron": "The Free Agents",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 22173,
  },
  {
    "name": "Ghost of a Chance",
    "requirements": [],
    "lvl": 25,
    "patron": "The Free Agents",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 20805,
  },
  {
    "name": "Precious Cargo",
    "requirements": [
      "A Legend Revisited",
      "Old Tomb, New Tenants",
      "Prove Your Worth",
      "Ghost of a Chance"
    ],
    "lvl": 25,
    "patron": "The Free Agents",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 20394,
  },
  {
    "name": "Epic Pirate Saga",
    "isSaga": true,
    "requirements": [
      "Storm the Beaches",
      "The Black Loch",
      "Bargain of Blood",
      "The Tide Turns",
      "Spies in the House",
      "A Legend Revisited",
      "Old Tomb, New Tenants",
      "Prove Your Worth",
      "Ghost of a Chance",
      "Precious Cargo"
    ],
    "xp": 92000
  },
  {
    "name": "The Fall of Truth",
    "requirements": [
      "Return to Madstone Crater",
      "Return to Prison of the Planes",
      "Return to Cabal for One",
      "Return to Gianthold Tor"
    ],
    "lvl": 25,
    "patron": "Agents of Argonnessen",
    "favor": 24,
    "difficulty": null,
    "baseXP": 29013,
  },
  {
    "name": "A Study in Sable",
    "requirements": [],
    "lvl": 26,
    "patron": "Purple Dragon Knights",
    "favor": 27,
    "difficulty": "R",
    "baseXP": 23905,
  },
  {
    "name": "Fashion Madness",
    "requirements": [],
    "lvl": 26,
    "patron": "The Twelve",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 19968,
  },
  {
    "name": "Terminal Delirium",
    "requirements": [],
    "lvl": 26,
    "patron": "The Twelve",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 31498,
  },
  {
    "name": "Palace of Stone",
    "requirements": [],
    "lvl": 26,
    "patron": "The Twelve",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 21937,
  },
  {
    "name": "Friends in Low Places",
    "requirements": [],
    "lvl": 26,
    "patron": "Purple Dragon Knights",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 28319,
  },
  {
    "name": "A Lesson in Deception",
    "requirements": [],
    "lvl": 26,
    "patron": "Purple Dragon Knights",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 19830,
  },
  {
    "name": "Army of Shadow",
    "requirements": [],
    "lvl": 26,
    "patron": "Purple Dragon Knights",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 23759,
  },
  {
    "name": "The Thrill of the Hunt",
    "requirements": [],
    "lvl": 26,
    "patron": "Purple Dragon Knights",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 18601,
  },
  {
    "name": "Through a Mirror Darkly",
    "requirements": [
      "Friends in Low Places",
      "A Lesson in Deception",
      "Army of Shadow",
      "The Thrill of the Hunt"
    ],
    "lvl": 26,
    "patron": "Purple Dragon Knights",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 44716,
  },
  {
    "name": "Epic Planeswalker Saga",
    "isSaga": true,
    "requirements": [
      "Beyond the Rift",
      "The Lost Thread",
      "Trial by Fury",
      "The Deal and the Demon",
      "Reclaiming the Rift",
      "A Stay at the Inn",
      "Lost in the Swamp",
      "Rest Stop",
      "Detour",
      "The End of the Road",
      "Through a Mirror Darkly"
    ],
    "xp": 102000
  },
  {
    "name": "The Mystery of Delera's Tomb",
    "requirements": [],
    "lvl": 27,
    "patron": "House Jorasco",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 21948,
  },
  {
    "name": "The Missing Party",
    "requirements": [
      "The Mystery of Delera's Tomb"
    ],
    "lvl": 27,
    "patron": "House Jorasco",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 30464,
  },
  {
    "name": "Free Delera",
    "requirements": [
      "The Mystery of Delera's Tomb",
      "The Missing Party"
    ],
    "lvl": 27,
    "patron": "House Jorasco",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 21948,
  },
  {
    "name": "Return to Delera's Tomb",
    "requirements": [
      "The Mystery of Delera's Tomb",
      "The Missing Party",
      "Free Delera"
    ],
    "lvl": 27,
    "patron": "House Jorasco",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 0,
  },
  {
    "name": "Thrall of the Necromancer",
    "requirements": [
      "The Mystery of Delera's Tomb",
      "The Missing Party",
      "Free Delera",
      "Return to Delera's Tomb"
    ],
    "lvl": 27,
    "patron": "House Jorasco",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 29092,
  },
  {
    "name": "The Promise of Fire",
    "requirements": [],
    "lvl": 27,
    "patron": "Morgrave University",
    "favor": 12,
    "difficulty": "R",
    "baseXP": 14234,
  },
  {
    "name": "The Tracker's Trap",
    "requirements": [],
    "lvl": 27,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 31494,
  },
  {
    "name": "Lines of Supply",
    "requirements": [],
    "lvl": 27,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 17283,
  },
  {
    "name": "Breaking the Ranks",
    "requirements": [],
    "lvl": 27,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 15613,
  },
  {
    "name": "A Break in the Ice",
    "requirements": [],
    "lvl": 27,
    "patron": "The Harpers",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 27643,
  },
  {
    "name": "What Goes Up",
    "requirements": [
      "The Tracker's Trap",
      "Lines of Supply",
      "Breaking the Ranks",
      "A Break in the Ice"
    ],
    "lvl": 27,
    "patron": "The Harpers",
    "favor": 21,
    "difficulty": "R",
    "baseXP": 64490,
  },
  {
    "name": "Epic Huntsilvers Saga",
    "isSaga": true,
    "requirements": [
      "The Druid's Curse",
      "Detour",
      "Rest Stop",
      "A Stay at the Inn",
      "Lost in the Swamp",
      "The End of the Road",
      "Friends in Low Places",
      "A Lesson in Deception",
      "Army of Shadow",
      "The Thrill of the Hunt",
      "Through a Mirror Darkly",
      "The Tracker's Trap",
      "Lines of Supply",
      "Breaking the Ranks",
      "A Break in the Ice",
      "What Goes Up"
    ],
    "xp": 165000
  },
  {
    "name": "Epic Perils of Cormyr Saga",
    "isSaga": true,
    "requirements": [
      "Impossible Demands",
      "The Unquiet Graves",
      "The Lost Thread",
      "The Battle for Eveningstar",
      "Don't Drink the Water",
      "In the Belly of the Beast",
      "Outbreak",
      "Overgrowth",
      "Thorn and Paw",
      "The Druid's Curse",
      "Detour",
      "Rest Stop",
      "A Stay at the Inn",
      "Lost in the Swamp",
      "The End of the Road",
      "Friends in Low Places",
      "A Lesson in Deception",
      "Army of Shadow",
      "The Thrill of the Hunt",
      "Through a Mirror Darkly",
      "The Tracker's Trap",
      "Lines of Supply",
      "Breaking the Ranks",
      "A Break in the Ice",
      "What Goes Up"
    ],
    "xp": 230000
  },
  {
    "name": "Brothers of the Forge",
    "requirements": [],
    "lvl": 28,
    "patron": "House Cannith",
    "favor": 27,
    "difficulty": "R",
    "baseXP": 18809,
  },
  {
    "name": "Tower of Frost",
    "requirements": [],
    "lvl": 28,
    "patron": "The Free Agents",
    "favor": 18,
    "difficulty": "R",
    "baseXP": 31406,
  },
  {
    "name": "The Haunted Halls of Eveningstar",
    "requirements": [],
    "lvl": 28,
    "patron": "The Harpers",
    "favor": 27,
    "difficulty": "R",
    "baseXP": 29332,
  },
  {
    "name": "Toil and Trouble",
    "requirements": [],
    "lvl": 28,
    "patron": "The Harpers",
    "favor": 9,
    "difficulty": "R",
    "baseXP": 16597,
  },
  {
    "name": "Dinosaur Crisis",
    "requirements": [],
    "lvl": 28,
    "patron": "The Free Agents",
    "favor": 15,
    "difficulty": "R",
    "baseXP": 16597,
  },
  {
    "name": "Inferno of the Damned",
    "requirements": [],
    "lvl": 29,
    "patron": "The Silver Flame",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 29013,
  },
  {
    "name": "Desecrated Temple of Vol",
    "requirements": [],
    "lvl": 29,
    "patron": "The Silver Flame",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 26277,
  },
  {
    "name": "Ghosts of Perdition",
    "requirements": [],
    "lvl": 29,
    "patron": "The Silver Flame",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 31749,
  },
  {
    "name": "Flesh Maker's Laboratory",
    "requirements": [],
    "lvl": 29,
    "patron": "The Silver Flame",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 26277,
  },
  {
    "name": "The Mask of Deception",
    "requirements": [],
    "lvl": 30,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 19479,
  },
  {
    "name": "Tavern Brawl",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 6594,
  },
  {
    "name": "Grim and Barett",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 21394,
  },
  {
    "name": "Subversion",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 29263,
  },
  {
    "name": "Multitude of Menace",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 27394,
  },
  {
    "name": "The Archons' Trial",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 27550,
  },
  {
    "name": "Demon Assault",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 19323,
  },
  {
    "name": "The Devil's Details",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 23665,
  },
  {
    "name": "Fire on Thunder Peak",
    "requirements": [],
    "lvl": 30,
    "patron": "Purple Dragon Knights",
    "favor": 9,
    "difficulty": "N",
    "baseXP": 18202,
  },
  {
    "name": "Temple of the Deathwyrm",
    "requirements": [],
    "lvl": 30,
    "patron": "Purple Dragon Knights",
    "favor": 27,
    "difficulty": null,
    "baseXP": 30821,
  },
  {
    "name": "The Mark of Death",
    "requirements": [
      "Inferno of the Damned",
      "Desecrated Temple of Vol",
      "Ghosts of Perdition",
      "Flesh Maker's Laboratory"
    ],
    "lvl": 30,
    "patron": "The Silver Flame",
    "favor": 27,
    "difficulty": null,
    "baseXP": 18202,
  },
  {
    "name": "Defiler of the Just",
    "requirements": [],
    "lvl": 30,
    "patron": "The Gatekeepers",
    "favor": 27,
    "difficulty": null,
    "baseXP": 18202,
  },
  {
    "name": "Slave Pits of the Undercity",
    "requirements": [],
    "lvl": 31,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 33800,
  },
  {
    "name": "Secret of the Slavers' Stockade",
    "requirements": [
      "Slave Pits of the Undercity"
    ],
    "lvl": 31,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 48165,
  },
  {
    "name": "Assault on the Aerie of the Slave Lords",
    "requirements": [
      "Slave Pits of the Undercity",
      "Secret of the Slavers' Stockade"
    ],
    "lvl": 31,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 33800,
  },
  {
    "name": "Night Falls on Stormreach",
    "requirements": [],
    "lvl": 31,
    "patron": "House Jorasco",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 21112,
  },
  {
    "name": "Quarantine",
    "requirements": [
      "Night Falls on Stormreach"
    ],
    "lvl": 31,
    "patron": "House Jorasco",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 18329,
  },
  {
    "name": "The Madness of Crowds",
    "requirements": [
      "Night Falls on Stormreach"
    ],
    "lvl": 31,
    "patron": "House Jorasco",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 18329,
  },
  {
    "name": "Age of Rage",
    "requirements": [
      "Night Falls on Stormreach"
    ],
    "lvl": 31,
    "patron": "House Jorasco",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 19676,
  },
  {
    "name": "Toxic Treatment",
    "requirements": [
      "Night Falls on Stormreach",
      "Quarantine",
      "The Madness of Crowds",
      "Age of Rage"
    ],
    "lvl": 31,
    "patron": "House Jorasco",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 26140,
  },
  {
    "name": "Black and Blue",
    "requirements": [],
    "lvl": 31,
    "patron": "Agents of Argonnessen",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 34758,
  },
  {
    "name": "The Newcomers",
    "requirements": [],
    "lvl": 31,
    "patron": "Agents of Argonnessen",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 38588,
  },
  {
    "name": "Memoirs of an Illusory Larcener",
    "requirements": [],
    "lvl": 31,
    "patron": "The Free Agents",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 21208,
  },
  {
    "name": "Search and Rescue",
    "requirements": [],
    "lvl": 31,
    "patron": "The Harpers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 29013,
  },
  {
    "name": "Good Intentions",
    "requirements": [],
    "lvl": 31,
    "patron": "The Free Agents",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 28613,
  },
  {
    "name": "Into the Mists",
    "requirements": [],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 9,
    "difficulty": "H",
    "baseXP": 7307,
  },
  {
    "name": "Death House",
    "requirements": [
      "Into the Mists"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 16805,
  },
  {
    "name": "Fresh-baked Dreams",
    "requirements": [
      "Into the Mists"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 16805,
  },
  {
    "name": "An Invitation to Dinner",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams"
    ],
    "lvl": 32,
    "patron": "Keepers of the Feather",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 49305,
  },
  {
    "name": "A Mad Tea Party",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 17841,
  },
  {
    "name": "A Raven at the Door",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 31885,
  },
  {
    "name": "Oath of Vengeance",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 30209,
  },
  {
    "name": "Sealed in Amber",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner",
      "A Mad Tea Party",
      "A Raven at the Door",
      "Oath of Vengeance"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 31885,
  },
  {
    "name": "The Final Vintage",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner",
      "A Mad Tea Party",
      "A Raven at the Door",
      "Oath of Vengeance",
      "Sealed in Amber"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 8265,
  },
  {
    "name": "Ravens' Bane",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner",
      "A Mad Tea Party",
      "A Raven at the Door",
      "Oath of Vengeance",
      "Sealed in Amber"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 21830,
  },
  {
    "name": "Wrath of the Earth",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner",
      "A Mad Tea Party",
      "A Raven at the Door",
      "Oath of Vengeance",
      "Sealed in Amber"
    ],
    "lvl": 32,
    "patron": "Keepers of the Feather",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 15702,
  },
  {
    "name": "Sunrise",
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "An Invitation to Dinner",
      "A Mad Tea Party",
      "A Raven at the Door",
      "Oath of Vengeance",
      "Sealed in Amber",
      "The Final Vintage",
      "Ravens' Bane",
      "Wrath of the Earth"
    ],
    "lvl": 31,
    "patron": "Keepers of the Feather",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 21352,
  },
  {
    "name": "Epic Ravenloft Saga",
    "isSaga": true,
    "requirements": [
      "Into the Mists",
      "Death House",
      "Fresh-baked Dreams",
      "A Mad Tea Party",
      "A Raven at the Door",
      "Oath of Vengeance",
      "Sealed in Amber",
      "The Final Vintage",
      "Ravens' Bane",
      "Sunrise",
      "Wrath of the Earth",
      "An Invitation to Dinner"
    ],
    "xp": 276000
  },
  {
    "name": "Strike Back",
    "requirements": [],
    "lvl": 31,
    "patron": "The Harpers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 27672,
  },
  {
    "name": "Third Time's a Charm",
    "requirements": [],
    "lvl": 31,
    "patron": "The Harpers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 27672,
  },
  {
    "name": "Graveyard Shift",
    "requirements": [],
    "lvl": 31,
    "patron": "The Harpers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 23458,
  },
  {
    "name": "Records of the Past",
    "requirements": [],
    "lvl": 31,
    "patron": "The Harpers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 24863,
  },
  {
    "name": "Desire in the Dark",
    "requirements": [
      "Strike Back",
      "Third Time's a Charm",
      "Graveyard Shift",
      "Records of the Past"
    ],
    "lvl": 31,
    "patron": "The Harpers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 27672,
  },
  {
    "name": "Creeping Death",
    "requirements": [],
    "lvl": 31,
    "patron": "The Twelve",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 27991,
  },
  {
    "name": "To Curse the Sky",
    "requirements": [],
    "lvl": 31,
    "patron": "House Deneith",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 31406,
  },
  {
    "name": "White Plume Mountain",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 40504,
  },
  {
    "name": "Dread Sea Scrolls",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 15702,
  },
  {
    "name": "Wake Me Up Inside",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 23027,
  },
  {
    "name": "Make Believe",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 21830,
  },
  {
    "name": "The Endless Revels",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 23027,
  },
  {
    "name": "The Knight Who Cried Windmill",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 9861,
  },
  {
    "name": "Combatting Corruption",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 6,
    "difficulty": "E",
    "baseXP": 11457,
  },
  {
    "name": "The Thornwright",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 9860,
  },
  {
    "name": "A Frosty Reception",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 30928,
  },
  {
    "name": "Quid Pro Quo",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 22429,
  },
  {
    "name": "The Icemount Curse",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 24225,
  },
  {
    "name": "Witch Hunt",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 23027,
  },
  {
    "name": "Needle in a Fey Stack",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 31885,
  },
  {
    "name": "The Legend of the Lost Locket",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 20633,
  },
  {
    "name": "Immortality Lessons",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 31885,
  },
  {
    "name": "Epic Feywild Saga",
    "isSaga": true,
    "requirements": [
      "Wake Me Up Inside",
      "Make Believe",
      "The Endless Revels",
      "The Knight Who Cried Windmill",
      "Combatting Corruption",
      "The Thornwright",
      "A Frosty Reception",
      "Quid Pro Quo",
      "The Icemount Curse",
      "Witch Hunt",
      "Needle in a Fey Stack",
      "The Legend of the Lost Locket",
      "Immortality Lessons"
    ],
    "xp": 276000
  },
  {
    "name": "Through the Tulgey Wood",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 23027,
  },
  {
    "name": "One Dame Thing After Another",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 21830,
  },
  {
    "name": "Lost at Sea",
    "requirements": [],
    "lvl": 32,
    "patron": "The Free Agents",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 14840,
  },
  {
    "name": "A Sharn Welcome",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 25422,
  },
  {
    "name": "Red Rain",
    "requirements": [
      "A Sharn Welcome"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 25422,
  },
  {
    "name": "Best Laid Plans",
    "requirements": [
      "A Sharn Welcome"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 29013,
  },
  {
    "name": "The Same Old Song",
    "requirements": [
      "A Sharn Welcome"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 25422,
  },
  {
    "name": "Just Business",
    "requirements": [
      "A Sharn Welcome",
      "Red Rain",
      "Best Laid Plans",
      "The Same Old Song"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 28329,
  },
  {
    "name": "No Refunds",
    "requirements": [
      "A Sharn Welcome",
      "Red Rain",
      "Best Laid Plans",
      "The Same Old Song",
      "Just Business"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 25422,
  },
  {
    "name": "House of Pain",
    "requirements": [
      "A Sharn Welcome",
      "Red Rain",
      "Best Laid Plans",
      "The Same Old Song",
      "Just Business"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 29013,
  },
  {
    "name": "Blown Deadline",
    "requirements": [
      "A Sharn Welcome",
      "Red Rain",
      "Best Laid Plans",
      "The Same Old Song",
      "Just Business"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 25422,
  },
  {
    "name": "Reach for the Sky",
    "requirements": [
      "A Sharn Welcome",
      "Red Rain",
      "Best Laid Plans",
      "The Same Old Song",
      "Just Business",
      "No Refunds",
      "House of Pain",
      "Blown Deadline"
    ],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 41940,
  },
  {
    "name": "Epic Sharn Saga",
    "isSaga": true,
    "requirements": [
      "A Sharn Welcome",
      "Red Rain",
      "Best Laid Plans",
      "The Same Old Song",
      "Just Business",
      "No Refunds",
      "House of Pain",
      "Blown Deadline",
      "Reach for the Sky"
    ],
    "xp": 276000
  },
  {
    "name": "Ruinous Schemes",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 12733,
  },
  {
    "name": "The Wraithcallers",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 10818,
  },
  {
    "name": "Smash and Burn",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 21830,
  },
  {
    "name": "Thralls of the Fungus Lord",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 21830,
  },
  {
    "name": "Scavenger Hunt",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 14968,
  },
  {
    "name": "The Magma Must Flow",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 12733,
  },
  {
    "name": "Roll Call",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 14968,
  },
  {
    "name": "Security Detail",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 12733,
  },
  {
    "name": "Epic Cogs Saga",
    "isSaga": true,
    "requirements": [
      "Ruinous Schemes",
      "The Wraithcallers",
      "Smash and Burn",
      "Thralls of the Fungus Lord",
      "Scavenger Hunt",
      "The Magma Must Flow",
      "Roll Call",
      "Security Detail"
    ],
    "xp": 276000
  },
  {
    "name": "An Element of Chaos",
    "requirements": [],
    "lvl": 32,
    "patron": "Morgrave University",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 17521,
  },
  {
    "name": "Beautiful Nightmares",
    "requirements": [],
    "lvl": 32,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 29013,
  },
  {
    "name": "Seizing the Dawn",
    "requirements": [],
    "lvl": 32,
    "patron": "Morgrave University",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 17521,
  },
  {
    "name": "Eye Know Whodunnit",
    "requirements": [],
    "lvl": 32,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 29013,
  },
  {
    "name": "The Home of Memory",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 11927,
  },
  {
    "name": "Rosemary's Ballad",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 12601,
  },
  {
    "name": "Heart of the Problem",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 12601,
  },
  {
    "name": "The Sacred Bounty",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "E",
    "baseXP": 11314,
  },
  {
    "name": "Housekeeping",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 13152,
  },
  {
    "name": "Soul Survivor",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 36194,
  },
  {
    "name": "The Offshore Account",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 18958,
  },
  {
    "name": "Members Only",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 18958,
  },
  {
    "name": "The Underlane Assignment",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 18958,
  },
  {
    "name": "Finding Dorris",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 36194,
  },
  {
    "name": "Safety in Numbers",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 14249,
  },
  {
    "name": "The Haunting of Saltmarsh",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 10898,
  },
  {
    "name": "Under the Cover of Darkness",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "E",
    "baseXP": 12853,
  },
  {
    "name": "What Sleeps Below",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 14050,
  },
  {
    "name": "Back to Basics",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 14050,
  },
  {
    "name": "Rest for the Night",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 14050,
  },
  {
    "name": "Swim at Your Own Risk",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 6,
    "difficulty": "E",
    "baseXP": 11656,
  },
  {
    "name": "Down You Go",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 14050,
  },
  {
    "name": "The Final Enemy",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 42179,
  },
  {
    "name": "The Hijacked Haul",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 14050,
  },
  {
    "name": "Danger at Dunwater",
    "requirements": [],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 36194,
  },
  {
    "name": "Epic Saltmarch Saga",
    "isSaga": true,
    "requirements": [
      "The Haunting of Saltmarsh",
      "Under the Cover of Darkness",
      "What Sleeps Below",
      "Back to Basics",
      "Rest for the Night",
      "Swim at Your Own Risk",
      "Down You Go",
      "The Final Enemy",
      "The Hijacked Haul",
      "Danger at Dunwater"
    ],
    "xp": 276000
  },
  {
    "name": "The Codex and the Shroud",
    "requirements": [
      "Creeping Death",
      "To Curse the Sky"
    ],
    "lvl": 32,
    "patron": "The Gatekeepers",
    "favor": 42,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Legendary Tempest's Spine",
    "requirements": [],
    "lvl": 32,
    "patron": "House Jorasco",
    "favor": 11,
    "difficulty": "N",
    "baseXP": 43285,
  },
  {
    "name": "Riding the Storm Out",
    "requirements": [],
    "lvl": 32,
    "patron": "Agents of Argonnessen",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Killing Time",
    "requirements": [],
    "lvl": 32,
    "patron": "Agents of Argonnessen",
    "favor": 33,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Old Baba's Hut",
    "requirements": [],
    "lvl": 32,
    "patron": "Keepers of the Feather",
    "favor": 27,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "The Curse of Strahd",
    "requirements": [],
    "lvl": 32,
    "patron": "Keepers of the Feather",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Project Nemesis",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Too Hot to Handle",
    "requirements": [],
    "lvl": 32,
    "patron": "Sharn City Council",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Legendary Vision of Destruction",
    "requirements": [],
    "lvl": 32,
    "patron": "The Twelve",
    "favor": 36,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Legendary Hound of Xoriat",
    "requirements": [],
    "lvl": 32,
    "patron": "The Twelve",
    "favor": 12,
    "difficulty": "N",
    "baseXP": 35340,
  },
  {
    "name": "Legendary Master Artificer",
    "requirements": [],
    "lvl": 32,
    "patron": "House Cannith",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Legendary Lord of Blades",
    "requirements": [],
    "lvl": 32,
    "patron": "House Cannith",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "The Dryad and the Demigod",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Hunt or Be Hunted",
    "requirements": [],
    "lvl": 32,
    "patron": "The Summer Court",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Order in the Court!",
    "requirements": [],
    "lvl": 33,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 24795,
  },
  {
    "name": "Army of Eternal Night",
    "requirements": [],
    "lvl": 33,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 24795,
  },
  {
    "name": "Three Paths to Battle",
    "requirements": [],
    "lvl": 33,
    "patron": "Morgrave University",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 33373,
  },
  {
    "name": "Growing Pains",
    "requirements": [],
    "lvl": 33,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 24795,
  },
  {
    "name": "The Hand and the Eyes",
    "requirements": [],
    "lvl": 33,
    "patron": "Morgrave University",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 33373,
  },
  {
    "name": "Captive of the Hidden God",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 21603,
  },
  {
    "name": "The Curse and the Captive Crustacean",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 18667,
  },
  {
    "name": "The Trouble with Tar Pits",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 22344,
  },
  {
    "name": "All Hail the King",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 26020,
  },
  {
    "name": "Spiders and Flies",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 22344,
  },
  {
    "name": "Trials of the Triceratops",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 24795,
  },
  {
    "name": "Wild Thing",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 9,
    "difficulty": "H",
    "baseXP": 19893,
  },
  {
    "name": "Whispers of Return",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 24795,
  },
  {
    "name": "Plundering Pirates' Point",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 23569,
  },
  {
    "name": "Bullywugs and Booby Traps",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 32148,
  },
  {
    "name": "The Stone Crypt Chronicle",
    "requirements": [],
    "lvl": 33,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 32638,
  },
  {
    "name": "Fall of the Forbidden Temple",
    "requirements": [],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 45429,
  },
  {
    "name": "Epic Dread Saga",
    "isSaga": true,
    "requirements": [
      "Captive of the Hidden God",
      "The Curse and the Captive Crustacean",
      "The Trouble with Tar Pits",
      "All Hail the King",
      "Spiders and Flies",
      "Trials of the Triceratops",
      "Wild Thing",
      "Whispers of Return",
      "Plundering Pirates' Point",
      "Bullywugs and Booby Traps",
      "The Stone Crypt Chronicle",
      "Fall of the Forbidden Temple"
    ],
    "xp": 276000
  },
  {
    "name": "Kill Ten Rats",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 16436,
  },
  {
    "name": "Diplomatic Impunity",
    "requirements": [],
    "lvl": 34,
    "patron": "The Coin Lords",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 21602,
  },
  {
    "name": "Frame Work",
    "requirements": [],
    "lvl": 34,
    "patron": "The Coin Lords",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 22857,
  },
  {
    "name": "Eyes of Stone",
    "requirements": [],
    "lvl": 34,
    "patron": "The Coin Lords",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 27371,
  },
  {
    "name": "Assault on Summerfield",
    "requirements": [],
    "lvl": 34,
    "patron": "The Coin Lords",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 18342,
  },
  {
    "name": "Blockade Buster",
    "requirements": [],
    "lvl": 34,
    "patron": "The Coin Lords",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 19095,
  },
  {
    "name": "Undermine",
    "requirements": [],
    "lvl": 34,
    "patron": "The Coin Lords",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 32889,
  },
  {
    "name": "Siegebreaker",
    "requirements": [
      "Assault on Summerfield",
      "Blockade Buster",
      "Undermine"
    ],
    "lvl": 34,
    "patron": "The Coin Lords",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 31634,
  },
  {
    "name": "ToEE: First Level and Earth Temple",
    "requirements": [],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 29377,
  },
  {
    "name": "ToEE: Lower Temple Complex",
    "requirements": [
      "ToEE: First Level and Earth Temple"
    ],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 52451,
  },
  {
    "name": "ToEE: Fire Node",
    "requirements": [
      "ToEE: First Level and Earth Temple",
      "ToEE: Lower Temple Complex"
    ],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 27873,
  },
  {
    "name": "ToEE: Earth Node",
    "requirements": [
      "ToEE: First Level and Earth Temple",
      "ToEE: Lower Temple Complex"
    ],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 27873,
  },
  {
    "name": "ToEE: Air Node",
    "requirements": [
      "ToEE: First Level and Earth Temple",
      "ToEE: Lower Temple Complex"
    ],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 27873,
  },
  {
    "name": "ToEE: Water Node",
    "requirements": [
      "ToEE: First Level and Earth Temple",
      "ToEE: Lower Temple Complex"
    ],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 15,
    "difficulty": "H",
    "baseXP": 27873,
  },
  {
    "name": "ToEE: Depths of the Temple",
    "requirements": [
      "ToEE: First Level and Earth Temple",
      "ToEE: Lower Temple Complex",
      "ToEE: Fire Node",
      "ToEE: Earth Node",
      "ToEE: Air Node",
      "ToEE: Water Node"
    ],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 12,
    "difficulty": "H",
    "baseXP": 25866,
  },
  {
    "name": "Turn the Page",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 26619,
  },
  {
    "name": "Grand Theft Aureon",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 21,
    "difficulty": "E",
    "baseXP": 35397,
  },
  {
    "name": "Vecna Unleashed",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 26619,
  },
  {
    "name": "Enemy of My Enemy",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 26619,
  },
  {
    "name": "Law and Order",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 36400,
  },
  {
    "name": "Taken in Hand",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 27371,
  },
  {
    "name": "The Bark and the Blade",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 21,
    "difficulty": "H",
    "baseXP": 35397,
  },
  {
    "name": "The Evil We Know",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 26619,
  },
  {
    "name": "Vecna Denied",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 21,
    "difficulty": "E",
    "baseXP": 37403,
  },
  {
    "name": "Paper Trail",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 22857,
  },
  {
    "name": "Party 101",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 13326,
  },
  {
    "name": "The Devils to Pay",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 13326,
  },
  {
    "name": "What Dreams May Come",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 12198,
  },
  {
    "name": "Epic University Saga",
    "isSaga": true,
    "requirements": [
      "Turn the Page",
      "Grand Theft Aureon",
      "Vecna Unleashed",
      "Enemy of My Enemy",
      "Law and Order",
      "Taken in Hand",
      "The Bark and the Blade",
      "The Evil We Know",
      "Vecna Denied",
      "Paper Trail",
      "Party 101",
      "The Devils to Pay",
      "What Dreams May Come"
    ],
    "xp": 276000
  },
  {
    "name": "Pilgrims' Peril",
    "requirements": [],
    "lvl": 34,
    "patron": "The Twelve",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 34143,
  },
  {
    "name": "Stolen Power",
    "requirements": [],
    "lvl": 34,
    "patron": "The Twelve",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 34143,
  },
  {
    "name": "Horde of the Illithid Controller",
    "requirements": [],
    "lvl": 34,
    "patron": "The Twelve",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 34143,
  },
  {
    "name": "Astral Ambush",
    "requirements": [],
    "lvl": 34,
    "patron": "The Twelve",
    "favor": 18,
    "difficulty": "H",
    "baseXP": 30380,
  },
  {
    "name": "Catastrophe",
    "requirements": [],
    "lvl": 34,
    "patron": "Agents of Argonnessen",
    "favor": 6,
    "difficulty": "H",
    "baseXP": 13075,
  },
  {
    "name": "Fred's First Date",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 21061,
  },
  {
    "name": "Too Many Cooks",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 19437,
  },
  {
    "name": "This Old Haunt",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 21061,
  },
  {
    "name": "Rats in a Cage",
    "requirements": [],
    "lvl": 34,
    "patron": "The Harpers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 17983,
  },
  {
    "name": "The Wizard's Labyrinth",
    "requirements": [],
    "lvl": 34,
    "patron": "The Harpers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 15674,
  },
  {
    "name": "The Knife's Edge",
    "requirements": [],
    "lvl": 34,
    "patron": "The Harpers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 19522,
  },
  {
    "name": "The Darkness and the Light",
    "requirements": [],
    "lvl": 35,
    "patron": "The Harpers",
    "favor": 9,
    "difficulty": "E",
    "baseXP": 24407,
  },
  {
    "name": "Skeletons in the Closet",
    "requirements": [],
    "lvl": 34,
    "patron": "The Gatekeepers",
    "favor": 30,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "Fires Over Morgrave",
    "requirements": [],
    "lvl": 34,
    "patron": "Morgrave University",
    "favor": null,
    "difficulty": null,
    "baseXP": null,
  },
  {
    "name": "The Safehold",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
  {
    "name": "Secrets of the Red Wizards",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 39615,
  },
  {
    "name": "Seeds of Decay",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
  {
    "name": "Death Hosts this Banquet",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
  {
    "name": "Ogmha's Song",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
  {
    "name": "The Key to the Mythal",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 21,
    "difficulty": "E",
    "baseXP": 44334,
  },
  {
    "name": "The House of Gems",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
  {
    "name": "Times Long Past",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 21,
    "difficulty": "E",
    "baseXP": 48529,
  },
  {
    "name": "The Zulkir's Plan",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 18,
    "difficulty": "E",
    "baseXP": 39615,
  },
  {
    "name": "Book Burning",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 12521,
  },
  {
    "name": "Ettercap Incursion",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
  {
    "name": "Portal to Below",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
  {
    "name": "Voices of the Dead",
    "requirements": [],
    "lvl": 35,
    "patron": "Cormanthor Elves",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 23883,
  },
    {
    "name": "Myth Drannor Saga",
    "isSaga": true,
    "requirements": [
      "The Safehold",
      "Death Hosts this Banquet",
      "Ogmha's Song",
      "The Key to the Mythal",
      "Secrets of the Red Wizards",
      "Voices of the Dead",
      "The House of Gems",
      "Times Long Past",
      "The Zulkir's Plan",
      "Book Burning",
      "Ettercap Incursion",
      "Seeds of Decay",
      "Portal to Below"
    ],
    "xp": 276000
  },
  {
    "name": "The Coveted Culvert",
    "requirements": [],
    "lvl": 35,
    "patron": "The Free Agents",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 19950,
  },
  {
    "name": "Sleeping with the Fishes",
    "requirements": [],
    "lvl": 35,
    "patron": "The Free Agents",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 26505,
  },
  {
    "name": "The Bodysnatchers",
    "requirements": [],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "Locked Away pt1",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "Locked Away pt2",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "A Light in the Attic",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "A Miner Sacrifice",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "The Wish",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 17537,
  },
  {
    "name": "Beneath the Streets",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 35112,
  },
  {
    "name": "Special Delivery",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "Zoo Creeper",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "Cold Snap",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "Ends and Means",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 25065,
  },
  {
    "name": "The Proper Authorities",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 17537,
  },
  {
    "name": "Snowfall and Sunlight",
    "requirements": [
      "The Bodysnatchers"
    ],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 35112,
  },
    {
    "name": "Lamordia Saga",
    "isSaga": true,
    "requirements": [
      "The Bodysnatchers",
      "Locked Away pt1",
      "Locked Away pt2",
      "A Light in the Attic",
      "A Miner Sacrifice",
      "The Wish",
      "Beneath the Streets",
      "Special Delivery",
      "Zoo Creeper",
      "Cold Snap",
      "Ends and Means",
      "The Proper Authorities",
      "Snowfall and Sunlight"
    ],
    "xp": 276000
  },
  {
    "name": "Body and Mind",
    "requirements": [],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 29218,
  },
  {
    "name": "Going Rogue",
    "requirements": [],
    "lvl": 36,
    "patron": "Agents of Argonnessen",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 17966,
  },
  {
    "name": "Wish Upon a Card",
    "requirements": [],
    "lvl": 36,
    "patron": "Agents of Argonnessen",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 16358,
  },
  {
    "name": "Burning Down the House",
    "requirements": [],
    "lvl": 36,
    "patron": "Agents of Argonnessen",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 18770,
  },
  {
    "name": "Thrall of Duty",
    "requirements": [],
    "lvl": 36,
    "patron": "Agents of Argonnessen",
    "favor": 15,
    "difficulty": "E",
    "baseXP": 27025,
  },
  {
    "name": "The Final Draw",
    "requirements": [
      "Going Rogue",
      "Wish Upon a Card",
      "Burning Down the House",
      "Thrall of Duty"
    ],
    "lvl": 36,
    "patron": "Agents of Argonnessen",
    "favor": 12,
    "difficulty": "E",
    "baseXP": 18770,
  },
  {
    "name": "Relentless",
    "requirements": [],
    "lvl": 36,
    "patron": "Keepers of Lamordia",
    "favor": 36,
    "difficulty": "E",
    "baseXP": 64580,
  }
];